version: "3.9"
services:
  web:
    build:
      context: ../testapp-ui
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build:
      context:  ../testapp-api
      dockerfile: .docker/Dockerfile
    ports:
      - "8081:3000"